version: 1.0.{build}
branches:
  only:
  - master
  
configuration: Release

platform: Any CPU

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))#

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
    my_secret:
        secure: A30P+NAbb+SCkjRPmXIUXhNur2tQdjlb+HUSVy/mxzjsUoS2o7tdKy+6M9/Vj+Da2e5PXS88cFddfqJ0gdEYbr/VVqY6rgK8+kKUNToRvv8=
    keystore:
        secure: 8GOpI38BADJ9fibFJdvWLj1/ZMzofzr6cGJTNWgWdqpl3WZua1oIw3HzZXmol768kfDqEJSKUF+wsAqn5N8PvFc1AhcrKvQEIZABElZni7U=
    alias:
        secure: oIlX+3JxAPyl6OsUXdH0qbwIDNm4JT1yncRVvvxhae8nqh2/ATFhNUwz0EcnBkQQG7JnMHhaP7naNeesL9F+DEEQGoJtwUSWeZ58sMeo1pA=
    hockeyapptoken:
        secure: K6rb/k6JxRVy1IW6aII7ErAsOjkawr43yqDjirSiPXiYcpaXyYVH+IOFMCOCajti
    hockeyappid:
        secure: 5MsriAk2pQXYG1LyHMUz8F0+7sJzgPR3ijduw13CBlYy8VQMDcfhd4DDrGamEmov
install:
- cmd: >-
    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt Secrets\com.scandysoft.keystore.enc -secret %my_secret%
xamarin:
  email: michele.scandura@outlook.com
  password:
    secure: vfXQ6F68vj+3TVYW7Z3cQw==
  android: true
  ios: true
build_script:
- cmd: >-
    nuget restore "c:\projects\heroes\Heroes\Core\Core\packages.config" -PackagesDirectory "c:\projects\heroes\Heroes\packages"
    
    nuget restore "c:\projects\heroes\Heroes\Core\Core.Droid\packages.config" -PackagesDirectory "c:\projects\heroes\Heroes\packages"
    
    nuget restore "c:\projects\heroes\Heroes\Heroes\Heroes\packages.config" -PackagesDirectory "c:\projects\heroes\Heroes\packages"
    
    nuget restore "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\packages.config" -PackagesDirectory "c:\projects\heroes\Heroes\packages"

    msbuild.exe "c:\projects\heroes\Heroes\Core\Core.Droid\Core.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:Clean
    
    msbuild.exe "c:\projects\heroes\Heroes\Core\Core.Droid\Core.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:Build
    
    msbuild.exe "c:\projects\heroes\Heroes\Core\Core.Droid\Core.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:UpdateAndroidResources
    
    msbuild.exe "c:\projects\heroes\Heroes\Core\Core.Droid\Core.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:Build
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\Heroes.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:Clean
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\Heroes.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:Build
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\Heroes.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:UpdateAndroidResources
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\Heroes.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:Build
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\Heroes.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:PackageForAndroid
    
    jarsigner.exe -verbose -sigalg SHA1withRSA -digestalg SHA1  -keystore Secrets\com.scandysoft.keystore -signedjar Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.apk Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.apk Heroes -storepass %keystore% -keypass %alias%
    
    "C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.1\zipalign.exe" -f -v 4 Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.apk Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.aligned.apk
artifacts:
- path: Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.aligned.apk
  name: APK
 
 deploy_script:
  cmd: >-
    curl \
      -F "status=2" \
      -F "notify=1" \
      -F "notes_type=0" \
      -F "ipa=@Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.aligned.apk" \
      -H "X-HockeyAppToken: %hockeyapptoken%" \
      https://rink.hockeyapp.net/api/2/apps/%hockeyappid%/app_versions/upload
    