version: 1.0.{build}
branches:
  only:
  - testAppveyor
configuration: Release
platform: Any CPU
environment:
    my_secret:
        secure: A30P+NAbb+SCkjRPmXIUXhNur2tQdjlb+HUSVy/mxzjsUoS2o7tdKy+6M9/Vj+Da2e5PXS88cFddfqJ0gdEYbr/VVqY6rgK8+kKUNToRvv8=
    keystore:
        secure: 8GOpI38BADJ9fibFJdvWLj1/ZMzofzr6cGJTNWgWdqpl3WZua1oIw3HzZXmol768kfDqEJSKUF+wsAqn5N8PvFc1AhcrKvQEIZABElZni7U=

install:
- cmd: >-
    install:

    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt Secrets\com.scandysoft.keystore.enc -secret %my_secret%
xamarin:
  email: michele.scandura@outlook.com
  password:
    secure: vfXQ6F68vj+3TVYW7Z3cQw==
  android: true
  ios: true
build_script:
- cmd: >-
    nuget restore "c:\projects\heroes\Heroes\Heroes.sln"
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes.sln" /p:Configuration=Release /t:Clean
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes.sln" /p:Configuration=Release
    
    msbuild.exe "c:\projects\heroes\Heroes\Heroes\Heroes.Droid\Heroes.Droid.csproj" /p:Configuration=Release /p:Platform=AnyCPU /t:PackageForAndroid

    jarsigner.exe -verbose -sigalg SHA1withRSA -digestalg SHA1  -keystore Secrets\com.scandysoft.keystore -signedjar Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.apk Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.apk publishingdoc -storepass %keystore%

    zipalign.exe' -f -v 4 Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.apk Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.signed.aligned.apk
artifacts:
- path: Heroes\Heroes\Heroes.Droid\bin\release\com.scandysoft.heroes.apk
  name: APK